## DecisionTree_Regressor_Classifier_50_startup_company

#### Import Libraries

In [765]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

#### Import Datasets

In [766]:
df = pd.read_csv('C:\\Users\\Lenovo\\Desktop\\Dataset\\50_Startups.csv')

In [767]:
df.head(2)

R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.2       136897.80        471784.10    New York  192261.83
1   162597.7       151377.59        443898.53  California  191792.06

##### Info

In [768]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   State            50 non-null     object 
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB


#### when we perform model on D.T ,  always keep in mind , 

#### 1.when less D.T. then not need to treate the outliers. if D.T is high then need to treate the outliers.
#### because large tree has overfitting issue so to avoid overfitting we do oulier treatment
#### 2.When we doing Encoding then we not use OneHotEncode....... because OneHot is use when linear model
#### 3.Feature Scaling is not used in D.T because Tree based model and tree based model is allocating whether that model is represent or not

#### Check ambiguity data

In [769]:
for col in df.columns:
    
    print('***************************',col,'**********************************')
    
    print()
    print()
    
    print(set(df[col].to_list()))
    
    print()
    print()

*************************** R&D Spend **********************************


{0.0, 66051.52, 20229.59, 119943.24, 73994.56, 15505.73, 86419.7, 64664.71, 101913.08, 142107.34, 38558.51, 542.05, 22177.74, 1315.46, 131876.9, 162597.7, 44069.95, 93863.75, 61994.48, 72107.6, 63408.86, 78389.47, 78013.11, 46014.02, 100671.96, 75328.87, 94657.16, 65605.48, 123334.88, 55493.95, 67532.53, 61136.38, 28754.33, 134615.46, 91992.39, 23640.93, 46426.07, 114523.61, 76253.86, 120542.52, 153441.51, 165349.2, 91749.16, 1000.23, 144372.41, 77044.01, 27892.92, 28663.76, 130298.13}


*************************** Administration **********************************


{110594.11, 156547.42, 135426.92, 108679.17, 144135.98, 91790.61, 118671.85, 103057.49, 118546.05, 152701.92, 127382.3, 105751.03, 101145.55, 65947.93, 122782.75, 51743.15, 139553.16, 91391.77, 82982.09, 153514.11, 153773.43, 157693.92, 145077.58, 154806.14, 85047.44, 115641.28, 96189.63, 136897.8, 129219.61, 135495.07, 153032.06, 113867.3, 127056.21

##### Insights : There is no any ambiguity value

### Data Preprocessing

### 1. Handling Missing values

In [770]:
df.isnull().sum()

R&D Spend          0
Administration     0
Marketing Spend    0
State              0
Profit             0
dtype: int64

#### Insights : There is no missing values

### 2. Handling characters(Encoding)

In [771]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   State            50 non-null     object 
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB


#### Make Category

In [772]:
df['State'].value_counts()

New York      17
California    17
Florida       16
Name: State, dtype: int64

In [773]:
df['State'] = df['State'].astype('category')

In [774]:
df['State'] = df['State'].cat.codes

#### After treating category

In [775]:
df['State'].value_counts()

2    17
0    17
1    16
Name: State, dtype: int64

In [776]:
df.head(2)

R&D Spend  Administration  Marketing Spend  State     Profit
0   165349.2       136897.80        471784.10      2  192261.83
1   162597.7       151377.59        443898.53      0  191792.06

#### 3.Handling Outliers

##### Here only 4 features and 1 target variable so tree splitted is very less . so thats why we are not treating outliers

#### splt data into independent and dependent variable

In [777]:
x = df.iloc[: , :-1]
y = df.iloc[: , -1]

In [778]:
x.head(2)

R&D Spend  Administration  Marketing Spend  State
0   165349.2       136897.80        471784.10      2
1   162597.7       151377.59        443898.53      0

In [779]:
y.head(2)

0    192261.83
1    191792.06
Name: Profit, dtype: float64

#### split data into train test split

In [780]:
from sklearn.model_selection import train_test_split

In [781]:
x_train,x_test,y_train,y_test = train_test_split(x , y , test_size = 0.25 , random_state = 1)

In [782]:
print(x_train.shape,x_test.shape,y_train.shape,y_test.shape)

(37, 4) (13, 4) (37,) (13,)


#### Building DecisionTree Model

In [783]:
from sklearn.tree import DecisionTreeRegressor

In [784]:
dt = DecisionTreeRegressor()

In [785]:
dt

DecisionTreeRegressor()

In [786]:
dt.fit(x_train , y_train)

DecisionTreeRegressor()

In [787]:
y_train_pred_dt = dt.predict(x_train)

In [788]:
y_train_pred_dt

array([ 90708.19, 122776.86,  71498.49,  14681.4 , 105733.54, 110352.25,
       134307.35,  77798.83, 125370.37,  64926.08, 108552.04, 108733.99,
       166187.94,  96778.92, 132602.65,  99937.59, 146121.95, 103282.38,
        65200.33,  96712.8 , 124266.9 , 118474.03, 107404.34, 156122.51,
       155752.6 ,  42559.73, 191792.06, 126992.93, 192261.83, 129917.04,
       156991.12, 144259.4 , 149759.96, 152211.77, 141585.52,  69758.98,
        89949.14])

#### Training Accuracy

In [789]:
from sklearn.metrics import r2_score

In [790]:
training_accuracy_dt = r2_score(y_train , y_train_pred_dt)

In [791]:
training_accuracy_dt

1.0

#### Testing Model

In [792]:
dt.fit(x_test , y_test)

DecisionTreeRegressor()

In [793]:
y_test_pred_dt = dt.predict(x_test)

In [794]:
y_test_pred_dt

array([105008.31,  96479.51,  78239.91,  81229.06, 191050.39, 182901.99,
        35673.41, 101004.64,  49490.75,  97483.56,  97427.84,  81005.76,
       111313.02])

#### Testing Accuracy

In [795]:
testing_accuracy_dt = r2_score(y_test , y_test_pred_dt)

In [796]:
testing_accuracy_dt

1.0

##### We get training accuracy is 1.0 and testing accuracy is 1.0

#### Here we get training accuracy 100 % and testing accuracy is 100%. so it is not possible to accuracy 100 % . so thats why we are not not go with resgressor model with decision Tree  

##### when we have regressor problem statement then avoid to use of DecisionTreeRegressor because it has overfitting problem

#### Cross val method to reduce overfitting (overfitting is the 100% training accuracy and 100% testing accuracy)

In [797]:
from sklearn.model_selection import cross_val_score

In [798]:
cs = cross_val_score(dt , x_train , y_train , cv = 10)

In [799]:
cs

array([  0.42443097,   0.87181169,   0.58740831,   0.86546022,
         0.96634384,   0.26438253,   0.92993926,   0.88695806,
       -21.22435468,   0.92581792])

In [800]:
cs.mean()

-1.4501801887358723

In [801]:
cs.max()

0.9663438399901733

##### Insights : Yes still our model is facing overfitting because it has more than 10 % variance in mean and max accuracy.

##### Yes we are not accept Decision Tree model

#### Building Linear Regression Model

In [802]:
from sklearn.linear_model import LinearRegression

In [803]:
lm = LinearRegression()

In [804]:
lm.fit(x_train , y_train)

LinearRegression()

In [805]:
y_train_pred_lm = lm.predict(x_train)

In [806]:
y_train_pred_lm

array([ 77575.85523541, 115265.75157209,  71607.5874736 ,  50142.12725225,
       110881.25819955, 115528.32761095, 127131.5256427 ,  75819.43007822,
       130964.77555205,  50272.60032435, 112869.58189044, 110673.17584432,
       169564.27127849,  98500.65370748, 148942.48442919,  99325.4351463 ,
       134348.1784066 , 103234.81538195,  66435.17602548,  90986.8289602 ,
       128788.71049663, 116696.78860153, 102481.64612999, 155435.86727647,
       159090.38121303,  48615.00001668, 187284.96554226, 116884.91502809,
       191146.36774105, 145438.48165266, 162056.95690315, 133701.90432789,
       152790.86835724, 151653.01177778, 128882.55588733,  62442.4211287 ,
        88863.12790791])

##### Training Accuracy

In [807]:
from sklearn.metrics import r2_score

In [808]:
training_accuracy_lm = r2_score(y_train , y_train_pred_lm)

In [809]:
training_accuracy_lm

0.9419507593691141

#### Testing Model

In [810]:
lm.fit(x_test , y_test)

LinearRegression()

In [811]:
y_test_pred_lm = lm.predict(x_test)

#### Testing Accuracy

In [812]:
testing_accuracy_lm = r2_score(y_test , y_test_pred_lm)

In [813]:
testing_accuracy_lm

0.9786060672473249

#### We get very accurate model beacause training accuracy is 94.19507593691141 and testing accuracy is 97.86060672473249. we have variance is approximate 3 % . when we have 10 % variance is training and testing accuracy i.e. Most Accurate Model. But , In linear regression we are not go with accuracy only we need to satisfy the assumptions as well.

##### But when we followed Linear Regression Model approach. we have to satisfy assumptions
##### Like , 
#### 1.Endoginity
#### 2.Homoscadasticity
#### 3.Normality of residual
#### 4.Normal Linearity
#### 5.No Autocorrelation
#### 6.Multicollinearity

#### Here we are not satisfy the any assumptions

### RandomFoestRegressor Model

##### RandomFoestRegressor Model is avoid overfitting problem that occure in DecisionTree.

In [814]:
from sklearn.ensemble import RandomForestRegressor

In [815]:
rf = RandomForestRegressor(n_estimators = 500)

In [816]:
rf

RandomForestRegressor(n_estimators=500)

In [817]:
rf.fit(x_train , y_train)

RandomForestRegressor(n_estimators=500)

In [818]:
y_train_pred_rf = rf.predict(x_train)

In [819]:
y_train_pred_rf

array([ 85465.13406, 126803.0864 ,  72824.4812 ,  32815.30826,
       108578.20824, 110776.785  , 133693.62172,  80025.38614,
       128023.47328,  55937.66704, 114827.33538, 108726.5957 ,
       162080.2081 ,  97899.65114, 138894.10126, 102104.03706,
       143874.07044, 104218.18838,  65864.30536,  95486.2333 ,
       127975.39378, 115228.8326 , 106728.0304 , 152060.1868 ,
       155215.0895 ,  40140.79074, 187458.94058, 122745.37896,
       185204.2187 , 133324.15002, 157799.10518, 143486.36564,
       149626.63046, 146921.80336, 137723.09658,  67955.08632,
        91894.5069 ])

#### Training Accuracy Randomforest

In [820]:
training_accuracy_rf = r2_score(y_train , y_train_pred_rf)

In [821]:
training_accuracy_rf

0.9855464157006457

#### Testing Model RandomForest

In [822]:
rf.fit(x_test , y_test)

RandomForestRegressor(n_estimators=500)

In [823]:
y_test_pred_rf = rf.predict(x_test)

In [824]:
y_test_pred_rf

array([112956.43246,  91587.2502 ,  81436.19108,  78466.60596,
       179710.2026 , 176561.92364,  45472.4687 ,  99939.9208 ,
        59733.9114 ,  98319.57026,  96317.7478 ,  84464.68302,
       108905.00036])

#### Testing Acuuracy RandomForest

In [825]:
testing_accuracy_rf = r2_score(y_test , y_test_pred_rf)

In [826]:
testing_accuracy_rf

0.9786530244839216

#### Insights : Here we get training accuracy of randomforest is 98.60323628181251 and testing accuracy randomforest is 97.66426451744701

#### Here we choose randomForest Model because it does not having any assumptions for satisfying as compare to Linearregression(In linear regression we have assumptions for satisfying)

### When we have any overfitting problem always go with (Bagging) Randomforest and when we have underfitting problem then we use (Boosting) XGBoost.